// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: cthulhu/agent/v1/agent.proto

// Package cthulhu.agent.v1 is the control-plane contract between the Panel and a
// node Agent. The Agent runs the gRPC server (one per host); the Panel dials it
// over mutual TLS. Request/response RPCs carry control actions; server-streaming
// RPCs carry install progress, console output, and resource telemetry.

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_GetNodeInfo_FullMethodName      = "/cthulhu.agent.v1.NodeService/GetNodeInfo"
	NodeService_CreateServer_FullMethodName     = "/cthulhu.agent.v1.NodeService/CreateServer"
	NodeService_RemoveServer_FullMethodName     = "/cthulhu.agent.v1.NodeService/RemoveServer"
	NodeService_ApplyConfig_FullMethodName      = "/cthulhu.agent.v1.NodeService/ApplyConfig"
	NodeService_ListFiles_FullMethodName        = "/cthulhu.agent.v1.NodeService/ListFiles"
	NodeService_DownloadFiles_FullMethodName    = "/cthulhu.agent.v1.NodeService/DownloadFiles"
	NodeService_ReadFile_FullMethodName         = "/cthulhu.agent.v1.NodeService/ReadFile"
	NodeService_DownloadFile_FullMethodName     = "/cthulhu.agent.v1.NodeService/DownloadFile"
	NodeService_MakeDir_FullMethodName          = "/cthulhu.agent.v1.NodeService/MakeDir"
	NodeService_MovePath_FullMethodName         = "/cthulhu.agent.v1.NodeService/MovePath"
	NodeService_CopyPath_FullMethodName         = "/cthulhu.agent.v1.NodeService/CopyPath"
	NodeService_WriteFile_FullMethodName        = "/cthulhu.agent.v1.NodeService/WriteFile"
	NodeService_DeletePaths_FullMethodName      = "/cthulhu.agent.v1.NodeService/DeletePaths"
	NodeService_CreateBackup_FullMethodName     = "/cthulhu.agent.v1.NodeService/CreateBackup"
	NodeService_ListBackups_FullMethodName      = "/cthulhu.agent.v1.NodeService/ListBackups"
	NodeService_RestoreBackup_FullMethodName    = "/cthulhu.agent.v1.NodeService/RestoreBackup"
	NodeService_DeleteBackup_FullMethodName     = "/cthulhu.agent.v1.NodeService/DeleteBackup"
	NodeService_InstallServer_FullMethodName    = "/cthulhu.agent.v1.NodeService/InstallServer"
	NodeService_PowerAction_FullMethodName      = "/cthulhu.agent.v1.NodeService/PowerAction"
	NodeService_GetServerStatus_FullMethodName  = "/cthulhu.agent.v1.NodeService/GetServerStatus"
	NodeService_StreamConsole_FullMethodName    = "/cthulhu.agent.v1.NodeService/StreamConsole"
	NodeService_SendCommand_FullMethodName      = "/cthulhu.agent.v1.NodeService/SendCommand"
	NodeService_StreamStats_FullMethodName      = "/cthulhu.agent.v1.NodeService/StreamStats"
	NodeService_ApplyNodeConfig_FullMethodName  = "/cthulhu.agent.v1.NodeService/ApplyNodeConfig"
	NodeService_ReplicateBackups_FullMethodName = "/cthulhu.agent.v1.NodeService/ReplicateBackups"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService is implemented by the Agent and consumed by the Panel.
type NodeServiceClient interface {
	// GetNodeInfo returns the node's identity and capacity. Used for health checks
	// and to reconcile the Panel's view of the node.
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*NodeInfo, error)
	// CreateServer records a server's runtime spec on the node and provisions its
	// data volume, without starting it. Must precede InstallServer/PowerAction.
	CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error)
	// RemoveServer stops and removes a server's container (and optionally its data).
	RemoveServer(ctx context.Context, in *RemoveServerRequest, opts ...grpc.CallOption) (*RemoveServerResponse, error)
	// ApplyConfig writes rendered game-config files into the server's data volume.
	// The Panel renders the content from the server's settings; the Agent just
	// persists the bytes at each path.
	ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error)
	// ListFiles lists the entries directly under a path in the server's volume.
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	// DownloadFiles streams a zip archive of the selected paths from the volume.
	DownloadFiles(ctx context.Context, in *DownloadFilesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// ReadFile returns the raw bytes of a single file in the volume, capped at
	// max_bytes. Used by the in-browser file editor/preview.
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	// DownloadFile streams the raw (unzipped) bytes of a single file for download.
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// MakeDir creates a directory (and parents) in the volume.
	MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*MakeDirResponse, error)
	// MovePath renames/moves a file or directory within the volume.
	MovePath(ctx context.Context, in *MovePathRequest, opts ...grpc.CallOption) (*MovePathResponse, error)
	// CopyPath copies a file or directory within the volume.
	CopyPath(ctx context.Context, in *CopyPathRequest, opts ...grpc.CallOption) (*CopyPathResponse, error)
	// WriteFile writes/overwrites a single file in the volume (new file or upload).
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	// DeletePaths removes files/directories (recursively) from the volume.
	DeletePaths(ctx context.Context, in *DeletePathsRequest, opts ...grpc.CallOption) (*DeletePathsResponse, error)
	// CreateBackup snapshots the server's data volume into a node-local archive.
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupInfo, error)
	// ListBackups lists a server's backups.
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	// RestoreBackup extracts a backup back into the server's data volume.
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error)
	// DeleteBackup removes a backup archive.
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error)
	// InstallServer runs the install/update phase for a server (e.g. SteamCMD) in
	// a one-shot container, streaming progress until completion or failure.
	InstallServer(ctx context.Context, in *InstallServerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstallEvent], error)
	// PowerAction performs a power transition (start/stop/restart/kill).
	PowerAction(ctx context.Context, in *PowerActionRequest, opts ...grpc.CallOption) (*PowerActionResponse, error)
	// GetServerStatus returns a server's current state and last-known resources.
	GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*ServerStatus, error)
	// StreamConsole streams console output for a server until the client cancels.
	StreamConsole(ctx context.Context, in *StreamConsoleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleLine], error)
	// SendCommand writes a command to a running server's console / stdin.
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error)
	// StreamStats streams periodic resource telemetry for a server.
	StreamStats(ctx context.Context, in *StreamStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceStats], error)
	// ApplyNodeConfig delivers the Panel-managed per-node configuration (backup
	// target selection + credentials, replication). The Agent applies it live and
	// validates reachability of the configured target, returning ok/detail.
	ApplyNodeConfig(ctx context.Context, in *ApplyNodeConfigRequest, opts ...grpc.CallOption) (*ApplyNodeConfigResponse, error)
	// ReplicateBackups mirrors a server's existing archives from the primary
	// target to the configured SFTP remote. Drives the scheduled "replicate"
	// cron action.
	ReplicateBackups(ctx context.Context, in *ReplicateBackupsRequest, opts ...grpc.CallOption) (*ReplicateBackupsResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*NodeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfo)
	err := c.cc.Invoke(ctx, NodeService_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServerResponse)
	err := c.cc.Invoke(ctx, NodeService_CreateServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RemoveServer(ctx context.Context, in *RemoveServerRequest, opts ...grpc.CallOption) (*RemoveServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveServerResponse)
	err := c.cc.Invoke(ctx, NodeService_RemoveServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyConfigResponse)
	err := c.cc.Invoke(ctx, NodeService_ApplyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, NodeService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DownloadFiles(ctx context.Context, in *DownloadFilesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_DownloadFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFilesRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_DownloadFilesClient = grpc.ServerStreamingClient[FileChunk]

func (c *nodeServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, NodeService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_DownloadFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *nodeServiceClient) MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*MakeDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeDirResponse)
	err := c.cc.Invoke(ctx, NodeService_MakeDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) MovePath(ctx context.Context, in *MovePathRequest, opts ...grpc.CallOption) (*MovePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MovePathResponse)
	err := c.cc.Invoke(ctx, NodeService_MovePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CopyPath(ctx context.Context, in *CopyPathRequest, opts ...grpc.CallOption) (*CopyPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyPathResponse)
	err := c.cc.Invoke(ctx, NodeService_CopyPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, NodeService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeletePaths(ctx context.Context, in *DeletePathsRequest, opts ...grpc.CallOption) (*DeletePathsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePathsResponse)
	err := c.cc.Invoke(ctx, NodeService_DeletePaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*BackupInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupInfo)
	err := c.cc.Invoke(ctx, NodeService_CreateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, NodeService_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreBackupResponse)
	err := c.cc.Invoke(ctx, NodeService_RestoreBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*DeleteBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBackupResponse)
	err := c.cc.Invoke(ctx, NodeService_DeleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) InstallServer(ctx context.Context, in *InstallServerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstallEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[2], NodeService_InstallServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstallServerRequest, InstallEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_InstallServerClient = grpc.ServerStreamingClient[InstallEvent]

func (c *nodeServiceClient) PowerAction(ctx context.Context, in *PowerActionRequest, opts ...grpc.CallOption) (*PowerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_PowerAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetServerStatus(ctx context.Context, in *GetServerStatusRequest, opts ...grpc.CallOption) (*ServerStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerStatus)
	err := c.cc.Invoke(ctx, NodeService_GetServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamConsole(ctx context.Context, in *StreamConsoleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[3], NodeService_StreamConsole_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConsoleRequest, ConsoleLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamConsoleClient = grpc.ServerStreamingClient[ConsoleLine]

func (c *nodeServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCommandResponse)
	err := c.cc.Invoke(ctx, NodeService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamStats(ctx context.Context, in *StreamStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[4], NodeService_StreamStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamStatsRequest, ResourceStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamStatsClient = grpc.ServerStreamingClient[ResourceStats]

func (c *nodeServiceClient) ApplyNodeConfig(ctx context.Context, in *ApplyNodeConfigRequest, opts ...grpc.CallOption) (*ApplyNodeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyNodeConfigResponse)
	err := c.cc.Invoke(ctx, NodeService_ApplyNodeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ReplicateBackups(ctx context.Context, in *ReplicateBackupsRequest, opts ...grpc.CallOption) (*ReplicateBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateBackupsResponse)
	err := c.cc.Invoke(ctx, NodeService_ReplicateBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService is implemented by the Agent and consumed by the Panel.
type NodeServiceServer interface {
	// GetNodeInfo returns the node's identity and capacity. Used for health checks
	// and to reconcile the Panel's view of the node.
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*NodeInfo, error)
	// CreateServer records a server's runtime spec on the node and provisions its
	// data volume, without starting it. Must precede InstallServer/PowerAction.
	CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error)
	// RemoveServer stops and removes a server's container (and optionally its data).
	RemoveServer(context.Context, *RemoveServerRequest) (*RemoveServerResponse, error)
	// ApplyConfig writes rendered game-config files into the server's data volume.
	// The Panel renders the content from the server's settings; the Agent just
	// persists the bytes at each path.
	ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error)
	// ListFiles lists the entries directly under a path in the server's volume.
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	// DownloadFiles streams a zip archive of the selected paths from the volume.
	DownloadFiles(*DownloadFilesRequest, grpc.ServerStreamingServer[FileChunk]) error
	// ReadFile returns the raw bytes of a single file in the volume, capped at
	// max_bytes. Used by the in-browser file editor/preview.
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	// DownloadFile streams the raw (unzipped) bytes of a single file for download.
	DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[FileChunk]) error
	// MakeDir creates a directory (and parents) in the volume.
	MakeDir(context.Context, *MakeDirRequest) (*MakeDirResponse, error)
	// MovePath renames/moves a file or directory within the volume.
	MovePath(context.Context, *MovePathRequest) (*MovePathResponse, error)
	// CopyPath copies a file or directory within the volume.
	CopyPath(context.Context, *CopyPathRequest) (*CopyPathResponse, error)
	// WriteFile writes/overwrites a single file in the volume (new file or upload).
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	// DeletePaths removes files/directories (recursively) from the volume.
	DeletePaths(context.Context, *DeletePathsRequest) (*DeletePathsResponse, error)
	// CreateBackup snapshots the server's data volume into a node-local archive.
	CreateBackup(context.Context, *CreateBackupRequest) (*BackupInfo, error)
	// ListBackups lists a server's backups.
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	// RestoreBackup extracts a backup back into the server's data volume.
	RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error)
	// DeleteBackup removes a backup archive.
	DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error)
	// InstallServer runs the install/update phase for a server (e.g. SteamCMD) in
	// a one-shot container, streaming progress until completion or failure.
	InstallServer(*InstallServerRequest, grpc.ServerStreamingServer[InstallEvent]) error
	// PowerAction performs a power transition (start/stop/restart/kill).
	PowerAction(context.Context, *PowerActionRequest) (*PowerActionResponse, error)
	// GetServerStatus returns a server's current state and last-known resources.
	GetServerStatus(context.Context, *GetServerStatusRequest) (*ServerStatus, error)
	// StreamConsole streams console output for a server until the client cancels.
	StreamConsole(*StreamConsoleRequest, grpc.ServerStreamingServer[ConsoleLine]) error
	// SendCommand writes a command to a running server's console / stdin.
	SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error)
	// StreamStats streams periodic resource telemetry for a server.
	StreamStats(*StreamStatsRequest, grpc.ServerStreamingServer[ResourceStats]) error
	// ApplyNodeConfig delivers the Panel-managed per-node configuration (backup
	// target selection + credentials, replication). The Agent applies it live and
	// validates reachability of the configured target, returning ok/detail.
	ApplyNodeConfig(context.Context, *ApplyNodeConfigRequest) (*ApplyNodeConfigResponse, error)
	// ReplicateBackups mirrors a server's existing archives from the primary
	// target to the configured SFTP remote. Drives the scheduled "replicate"
	// cron action.
	ReplicateBackups(context.Context, *ReplicateBackupsRequest) (*ReplicateBackupsResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*NodeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedNodeServiceServer) CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServer not implemented")
}
func (UnimplementedNodeServiceServer) RemoveServer(context.Context, *RemoveServerRequest) (*RemoveServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveServer not implemented")
}
func (UnimplementedNodeServiceServer) ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyConfig not implemented")
}
func (UnimplementedNodeServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedNodeServiceServer) DownloadFiles(*DownloadFilesRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFiles not implemented")
}
func (UnimplementedNodeServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedNodeServiceServer) DownloadFile(*DownloadFileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedNodeServiceServer) MakeDir(context.Context, *MakeDirRequest) (*MakeDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeDir not implemented")
}
func (UnimplementedNodeServiceServer) MovePath(context.Context, *MovePathRequest) (*MovePathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MovePath not implemented")
}
func (UnimplementedNodeServiceServer) CopyPath(context.Context, *CopyPathRequest) (*CopyPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyPath not implemented")
}
func (UnimplementedNodeServiceServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedNodeServiceServer) DeletePaths(context.Context, *DeletePathsRequest) (*DeletePathsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePaths not implemented")
}
func (UnimplementedNodeServiceServer) CreateBackup(context.Context, *CreateBackupRequest) (*BackupInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedNodeServiceServer) ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedNodeServiceServer) RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (UnimplementedNodeServiceServer) DeleteBackup(context.Context, *DeleteBackupRequest) (*DeleteBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedNodeServiceServer) InstallServer(*InstallServerRequest, grpc.ServerStreamingServer[InstallEvent]) error {
	return status.Error(codes.Unimplemented, "method InstallServer not implemented")
}
func (UnimplementedNodeServiceServer) PowerAction(context.Context, *PowerActionRequest) (*PowerActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PowerAction not implemented")
}
func (UnimplementedNodeServiceServer) GetServerStatus(context.Context, *GetServerStatusRequest) (*ServerStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedNodeServiceServer) StreamConsole(*StreamConsoleRequest, grpc.ServerStreamingServer[ConsoleLine]) error {
	return status.Error(codes.Unimplemented, "method StreamConsole not implemented")
}
func (UnimplementedNodeServiceServer) SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedNodeServiceServer) StreamStats(*StreamStatsRequest, grpc.ServerStreamingServer[ResourceStats]) error {
	return status.Error(codes.Unimplemented, "method StreamStats not implemented")
}
func (UnimplementedNodeServiceServer) ApplyNodeConfig(context.Context, *ApplyNodeConfigRequest) (*ApplyNodeConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyNodeConfig not implemented")
}
func (UnimplementedNodeServiceServer) ReplicateBackups(context.Context, *ReplicateBackupsRequest) (*ReplicateBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateBackups not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CreateServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateServer(ctx, req.(*CreateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RemoveServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RemoveServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RemoveServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RemoveServer(ctx, req.(*RemoveServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ApplyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ApplyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ApplyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ApplyConfig(ctx, req.(*ApplyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DownloadFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFilesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).DownloadFiles(m, &grpc.GenericServerStream[DownloadFilesRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_DownloadFilesServer = grpc.ServerStreamingServer[FileChunk]

func _NodeService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).DownloadFile(m, &grpc.GenericServerStream[DownloadFileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_DownloadFileServer = grpc.ServerStreamingServer[FileChunk]

func _NodeService_MakeDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).MakeDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_MakeDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).MakeDir(ctx, req.(*MakeDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_MovePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).MovePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_MovePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).MovePath(ctx, req.(*MovePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CopyPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CopyPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CopyPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CopyPath(ctx, req.(*CopyPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeletePaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeletePaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeletePaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeletePaths(ctx, req.(*DeletePathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CreateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RestoreBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_DeleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_InstallServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstallServerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).InstallServer(m, &grpc.GenericServerStream[InstallServerRequest, InstallEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_InstallServerServer = grpc.ServerStreamingServer[InstallEvent]

func _NodeService_PowerAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).PowerAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_PowerAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).PowerAction(ctx, req.(*PowerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetServerStatus(ctx, req.(*GetServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamConsole_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConsoleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).StreamConsole(m, &grpc.GenericServerStream[StreamConsoleRequest, ConsoleLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamConsoleServer = grpc.ServerStreamingServer[ConsoleLine]

func _NodeService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).StreamStats(m, &grpc.GenericServerStream[StreamStatsRequest, ResourceStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamStatsServer = grpc.ServerStreamingServer[ResourceStats]

func _NodeService_ApplyNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ApplyNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ApplyNodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ApplyNodeConfig(ctx, req.(*ApplyNodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ReplicateBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ReplicateBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ReplicateBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ReplicateBackups(ctx, req.(*ReplicateBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cthulhu.agent.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _NodeService_GetNodeInfo_Handler,
		},
		{
			MethodName: "CreateServer",
			Handler:    _NodeService_CreateServer_Handler,
		},
		{
			MethodName: "RemoveServer",
			Handler:    _NodeService_RemoveServer_Handler,
		},
		{
			MethodName: "ApplyConfig",
			Handler:    _NodeService_ApplyConfig_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _NodeService_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _NodeService_ReadFile_Handler,
		},
		{
			MethodName: "MakeDir",
			Handler:    _NodeService_MakeDir_Handler,
		},
		{
			MethodName: "MovePath",
			Handler:    _NodeService_MovePath_Handler,
		},
		{
			MethodName: "CopyPath",
			Handler:    _NodeService_CopyPath_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _NodeService_WriteFile_Handler,
		},
		{
			MethodName: "DeletePaths",
			Handler:    _NodeService_DeletePaths_Handler,
		},
		{
			MethodName: "CreateBackup",
			Handler:    _NodeService_CreateBackup_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _NodeService_ListBackups_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _NodeService_RestoreBackup_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _NodeService_DeleteBackup_Handler,
		},
		{
			MethodName: "PowerAction",
			Handler:    _NodeService_PowerAction_Handler,
		},
		{
			MethodName: "GetServerStatus",
			Handler:    _NodeService_GetServerStatus_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _NodeService_SendCommand_Handler,
		},
		{
			MethodName: "ApplyNodeConfig",
			Handler:    _NodeService_ApplyNodeConfig_Handler,
		},
		{
			MethodName: "ReplicateBackups",
			Handler:    _NodeService_ReplicateBackups_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFiles",
			Handler:       _NodeService_DownloadFiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _NodeService_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstallServer",
			Handler:       _NodeService_InstallServer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamConsole",
			Handler:       _NodeService_StreamConsole_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamStats",
			Handler:       _NodeService_StreamStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cthulhu/agent/v1/agent.proto",
}
